on: [push, pull_request]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Check empty files
    steps:
      - name: Checking
        run: |
         for file in ./*.py ./**/*.py; \
         do if [ -s $file ]; \
         then echo $file; echo '$file is empty!' exit 1; \
         fi; done;
