on: [push, pull_request]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: Check empty files
    steps:
      - name: Checking
        run: |
          if find . -name "*.py" -type f -empty | grep ".*"; then
              echo Empty files above 🥹 ^^
              exit 1
          else
              echo Success!
          fi
